# options for analysis running
run:
  tests: false

output:
  print-issued-lines: false

linters:
  enable:
    - interfacer
    - unconvert
    - goconst
    - misspell
    - nakedret
    - prealloc
  disable:
    - errcheck
    - staticcheck
