language: go
sudo: required

go:
  - 1.7

env:
  - MIGRATE_TEST_CONTAINER_BOOT_DELAY=15

# TODO: https://docs.docker.com/engine/installation/linux/ubuntu/    
# pre-provision with travis docker setup and pin down docker version in install step
services:
  - docker 

install:
  - make deps
  - (cd $GOPATH/src/github.com/docker/docker && git fetch --all --tags --prune && git checkout v1.13.0)
  - sudo apt-get update && sudo apt-get install docker-engine=1.13.0*
  - go get github.com/mattn/goveralls 

script:
  - make test

after_success:
  - goveralls -service=travis-ci -coverprofile .coverage/combined.txt

before_deploy:
  - make build-cli

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: EFow50BI448HVb/uQ1Kk2Kq0xzmwIYq3V67YyymXIuqSCodvXEsMiBPUoLrxEknpPEIc67LEQTNdfHBgvyHk6oRINWAfie+7pr5tKrpOTF9ghyxoN1PlO8WKQCqwCvGMBCnc5ur5rvzp0bqfpV2rs5q9/nngy3kBuEvs12V7iho=
  on:
    repo: mattes/migrate
    tags: true
  file: 
    - cli/build/migrate.linux-amd64.tar.gz
    - cli/build/migrate.darwin-amd64.tar.gz
    - cli/build/migrate.windows-amd64.exe.tar.gz
    - cli/build/sha256sum.txt

