language: go
sudo: required

go:
  - 1.8
  - 1.9

env:
  - MIGRATE_TEST_CONTAINER_BOOT_TIMEOUT=60

# TODO: https://docs.docker.com/engine/installation/linux/ubuntu/    
# pre-provision with travis docker setup and pin down docker version in install step
services:
  - docker

before_cache:
  - mv $GOPATH/src/github.com/golang-migrate /tmp/golang-migrate
  - rm -rf $GOPATH/pkg/**/github.com/golang-migrate

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
  - make deps
  - (cd $GOPATH/src/github.com/docker/docker && git fetch --all --tags --prune && git checkout v17.05.0-ce)
  - sudo apt-get update && sudo apt-get --allow-downgrades install docker-ce=17.05.0*
  - go get github.com/mattn/goveralls 

script:
  - make test COVERAGE_DIR=/tmp/coverage

after_success:
  - mv /tmp/golang-migrate $GOPATH/src/github.com/golang-migrate
  - goveralls -service=travis-ci -coverprofile /tmp/coverage/combined.txt
  - make list-external-deps > dependency_tree.txt && cat dependency_tree.txt

before_deploy:
  - make build-cli
  - gem install --no-ri --no-rdoc fpm 
  - fpm -s dir -t deb -n migrate -v "$(git describe --tags 2>/dev/null | cut -c 2-)" --license MIT -m matthias.kadenbach@gmail.com --url https://github.com/mattes/migrate --description='Database migrations' -a amd64 -p migrate.$(git describe --tags 2>/dev/null | cut -c 2-).deb --deb-no-default-config-files -f -C cli/build migrate.linux-amd64=/usr/bin/migrate

deploy:
  - provider: releases
    api_key:
      secure: hWH1HLPpzpfA8pXQ93T1qKQVFSpQp0as/JLQ7D91jHuJ8p+RxVeqblDrR6HQY/95R/nyiE9GJmvUolSuw5h449LSrGxPtVWhdh6EnkxlQHlen5XeMhVjRjFV0sE9qGe8v7uAkiTfRO61ktTWHrEAvw5qpyqnNISodmZS78XIasPODQbNlzwINhWhDTHIjXGb4FpizYaL3OGCanrxfR9fQyCaqKGGBjRq3Mfq8U6Yd4mApmsE+uJxgaZV8K5zBqpkSzQRWhcVGNL5DuLsU3gfSJOo7kZeA2G71SHffH577dBoqtCZ4VFv169CoUZehLWCb+7XKJZmHXVujCURATSySLGUOPc6EoLFAn3YtsCA04mS4bZVo5FZPWVwfhjmkhtDR4f6wscKp7r1HsFHSOgm59QfETQdrn4MnZ44H2Jd39axqndn5DvK9EcZVjPHynOPnueXP2u6mTuUgh2VyyWBCDO3CNo0fGlo7VJI69IkIWNSD87K9cHZWYMClyKZkUzS+PmRAhHRYbVd+9ZjKOmnU36kUHNDG/ft1D4ogsY+rhVtXB4lgWDM5adri+EIScYdYnB1/pQexLBigcJY9uE7nQTR0U6QgVNYvun7uRNs40E0c4voSfmPdFO0FlOD2y1oQhnaXfWLbu9nMcTcs4RFGrcC7NzkUN4/WjG8s285V6w=
    skip_cleanup: true
    on:
      go: 1.9
      repo: golang-migrate/migrate
      tags: true
    file:
      - cli/build/migrate.linux-amd64.tar.gz
      - cli/build/migrate.darwin-amd64.tar.gz
      - cli/build/migrate.windows-amd64.exe.tar.gz
      - cli/build/sha256sum.txt
      - dependency_tree.txt
  - provider: packagecloud
    repository: migrate
    username: mattes
    token:
      secure: RiHJ/+J9DvXUah/APYdWySWZ5uOOISYJ0wS7xddc7/BNStRVjzFzvJ9zmb67RkyZZrvGuVjPiL4T8mtDyCJCj47RmU/56wPdEHbar/FjsiUCgwvR19RlulkgbV4okBCePbwzMw6HNHRp14TzfQCPtnN4kef0lOI4gZJkImN7rtQ=
    dist: ubuntu/xenial
    package_glob: '*.deb'
    skip_cleanup: true
    on:
      go: 1.9
      repo: mattes/migrate
      tags: true

